SKILL_KEYWORDS = [
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "angular",
    "vue",
    "node.js",
    "flask",
    "django",
    "fastapi",
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "git",
    "github",
    "ci/cd",
    "jenkins",
    "terraform",
    "linux",
    "rest",
    "graphql",
    "pandas",
    "numpy",
    "scikit-learn",
    "machine learning",
    "deep learning",
    "nlp",
    "computer vision",
    "data analysis",
    "power bi",
    "tableau",
    "spark",
    "hadoop",
    "microservices",
    "system design",
    "agile",
]
